[tool.poetry]
name = "inversion-sst-gp"
version = "0.2.0"
description = ""
authors = ["Rick de Kreij <r.d.kreij@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "inversion_sst_gp", from = "pkg" }]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = ">=2.2.5"
xarray = ">=2025.4.0"
matplotlib = ">=3.10.3"
pandas = ">=2.2.3"
netcdf4 = ">=1.7.2"
geographiclib = ">=2.0"
cmocean = ">=4.0.3"
scipy = ">=1.15.3"
colorcet = ">=3.1.0"
dask = ">=2025.5.1"
imageio = ">=2.37.2"
imageio-ffmpeg = ">=0.6.0"
rfgen = ">=0.1.6"
powspec = ">=0.3"
astropy = "<7"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
